services:
  music-server:
    container_name: music-server-jio
    restart: always
    image: auenkr/jio-savan-api
    ports:
      - 7005:3000

  application:
    container_name: sound-cast
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - path: ./apps/web/.env
        required: true
    ports:
      - 7000:3000
      - 7080:8080
